Repository Automattic/remote-data-blocks, pull requests merged in 2025-04, with the labels that each got.

#428 Remote Data Template block
  docs/ai.md
  docs/extending/block-registration.md
  example/google-sheets/westeros-houses/register.php
  inc/Editor/BlockManagement/BlockRegistration.php
  inc/Editor/BlockManagement/ConfigRegistry.php
  inc/Editor/DataBinding/BlockBindings.php
  inc/Integrations/Airtable/AirtableIntegration.php
  inc/Integrations/Airtable/templates/block_registration.template
  inc/Integrations/Google/Sheets/GoogleSheetsIntegration.php
  inc/Integrations/Google/Sheets/templates/block_registration.template
  inc/Validation/ConfigSchemas.php
  psalm.xml
  src/block-editor/filters/withBlockBinding.tsx
  src/block-editor/format-types/field-shortcode/components/FieldShortcodeSelectNew.tsx
  src/blocks/remote-data-container/block.json
  src/blocks/remote-data-container/components/InnerBlocks.tsx
  src/blocks/remote-data-container/components/placeholders/ItemSelectQueryType.tsx
  src/blocks/remote-data-container/components/placeholders/Placeholder.tsx
  src/blocks/remote-data-container/context/LoopIndexContext.ts
  src/blocks/remote-data-container/edit.tsx
  src/blocks/remote-data-container/editor.scss
  src/blocks/remote-data-container/hooks/usePatterns.ts
  src/blocks/remote-data-container/hooks/useRemoteDataContext.ts
  src/blocks/remote-data-container/render.php
  src/blocks/remote-data-template/block.json
  src/blocks/remote-data-template/components/item-preview/ItemPreview.tsx
  src/blocks/remote-data-template/components/loop-template/LoopTemplate.tsx
  src/blocks/remote-data-template/components/loop-template/LoopTemplateInnerBlocks.tsx
  src/blocks/remote-data-template/context/PreviewIndexContext.ts
  src/blocks/remote-data-template/edit.tsx
  src/blocks/remote-data-template/editor.scss
  src/blocks/remote-data-template/filters/index.ts
  src/blocks/remote-data-template/filters/withPreviewIndex.tsx
  src/blocks/remote-data-template/hooks/useGetInnerBlocks.ts
  src/blocks/remote-data-template/index.ts
  src/blocks/remote-data-template/render.php
  src/blocks/remote-data-template/save.tsx
  src/blocks/remote-html/render.php
  src/utils/block-binding.ts
  tests/inc/Functions/FunctionsTest.php
  tests/src/block-editor/filters/withBlockBinding.test.tsx
  tests/src/blocks/remote-data-template/components/loop-template/LoopTemplate.test.tsx
  tests/src/blocks/remote-data-template/components/loop-template/LoopTemplateInnerBlocks.test.tsx
  types/localized-block-data.d.ts
  types/remote-data.d.ts
Labels: enhancement

#457 Fix block name regression
  inc/Editor/BlockManagement/ConfigRegistry.php
  inc/Editor/BlockManagement/ConfigStore.php
  tests/integration/blocks/BlockConfigTest.php
Labels: bug

#463 Documentation updating Cache link and adding example
  docs/concepts/index.md
  docs/extending/query.md
Labels: documentation

#466 Docs: update AI documentation
  docs/ai.md
Labels: documentation

#478 Bugfix: Set default path based on whether the schema targets a collection
  inc/Config/QueryRunner/QueryResponseParser.php
  tests/inc/Config/QueryRunnerTest.php
Labels: bug

#477 Bugfix: Avoid repeated render of dynamic blocks
  inc/Config/QueryRunner/QueryResponseParser.php
  inc/Editor/DataBinding/BlockBindings.php
  tests/integration/RDBTestCase.php
  tests/integration/blocks/RemoteDataTemplateBlockTest.php
  tests/integration/blocks/RemoteHtmlBlockTest.php
Labels: bug
